name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          poetry install --no-root

      - name: Run static code checks
        run: |
          source $HOME/.poetry/env
          make check

      - name: Run unit tests
        run: |
          source $HOME/.poetry/env
          make unit-test
